#cloud-config

coreos:
  units:
    - name: kubelet.service
      enable: true
      command: start
      content: |
        [Service]
        EnvironmentFile=/etc/environment
        Environment=KUBELET_IMAGE_URL=quay.io/coreos/hyperkube
        Environment=KUBELET_IMAGE_TAG=v1.10.0_coreos.0
        Environment="RKT_RUN_ARGS=--uuid-file-save=/var/run/kubelet-pod.uuid \
          --volume etc-resolv,kind=host,source=/etc/resolv.conf \
          --mount volume=etc-resolv,target=/etc/resolv.conf \
          --volume var-lib-cni,kind=host,source=/var/lib/cni \
          --mount volume=var-lib-cni,target=/var/lib/cni \
          --volume var-lib-kubelet,kind=host,source=/var/lib/kubelet \
          --mount volume=var-lib-kubelet,target=/var/lib/kubelet"
        ExecStartPre=/bin/mkdir -p /etc/kubernetes/manifests
        ExecStartPre=/bin/mkdir -p /etc/kubernetes/cni/net.d
        ExecStartPre=/bin/mkdir -p /etc/kubernetes/checkpoint-secrets
        ExecStartPre=/bin/mkdir -p /etc/kubernetes/inactive-manifests
        ExecStartPre=/bin/mkdir -p /var/lib/kubelet/pki
        ExecStartPre=/bin/mkdir -p /var/lib/cni
        ExecStartPre=-/usr/bin/rkt rm --uuid-file=/var/run/kubelet-pod.uuid
        ExecStart=/usr/lib/coreos/kubelet-wrapper \
          --kubeconfig=/etc/kubernetes/kubeconfig \
          --client-ca-file=/etc/kubernetes/ca.crt \
          --anonymous-auth=false \
          --cert-dir=/var/lib/kubelet/pki \
          --cni-conf-dir=/etc/kubernetes/cni/net.d \
          --network-plugin=cni \
          --lock-file=/var/run/lock/kubelet.lock \
          --exit-on-lock-contention \
          --pod-manifest-path=/etc/kubernetes/manifests \
          --allow-privileged \
          --minimum-container-ttl-duration=3m0s \
          --hostname-override=${COREOS_PUBLIC_IPV4} \
          --node-labels=node-role.kubernetes.io/TYPE \
          --register-with-taints=node-role.kubernetes.io/master=:NoSchedule \
          --cluster_dns=10.3.0.10 \
          --cluster_domain=cluster.local \
          --rotate-certificates

        ExecStop=-/usr/bin/rkt stop --uuid-file=/var/run/kubelet-pod.uuid
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target
